//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMana.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuyenCongTac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChuyenCongTac()
        {
            this.NhanVien = new HashSet<NhanVien>();
        }
    
        public int soQuyetDinh { get; set; }
        public Nullable<System.DateTime> ngayQuyetDinh { get; set; }
        public string chucVuCu { get; set; }
        public string phongBanCu { get; set; }
        public string chucVuMoi { get; set; }
        public string phongBanMoi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanVien> NhanVien { get; set; }
    }
}
