//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMana.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoSo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoSo()
        {
            this.NhanVien = new HashSet<NhanVien>();
        }
    
        public int maHoSo { get; set; }
        public string soYeuLyLich { get; set; }
        public string giayKhaiSinh { get; set; }
        public string soHoKhau { get; set; }
        public string bangTotNghiep { get; set; }
        public string giayKhamSK { get; set; }
        public string anhThe { get; set; }
        public string tinhTrangHoSo { get; set; }
        public string hinhThucThanhToanLuong { get; set; }
        public string soTkNganHang { get; set; }
        public string nganHang { get; set; }
        public string tinhTrangHonNhan { get; set; }
        public string maSoThue { get; set; }
        public string maSoBHXH { get; set; }
        public Nullable<System.DateTime> ngayBatDauLamViec { get; set; }
        public string kinhNghiemLamViec { get; set; }
        public Nullable<System.DateTime> thoiGian { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanVien> NhanVien { get; set; }
    }
}
